model: yolov8m.pt
data: cv_module/dataset/dataset/data.yaml
hyp: cv_module/training/hyp_yolov8.yaml
imgsz: 704
epochs: 150
patience: 25
batch: 12
workers: 8
device: "0"
name: yolov8m
seed: 42
project: cv_module/models
half: true