model: cv_module/models/yolov8m/weights/best.pt
data: cv_module/dataset/dataset/data.yaml
hyp: cv_module/training/hyp_yolov8_post_train.yaml
imgsz: 768
epochs: 10
patience: 3
batch: 8
workers: 8
device: "0"
name: yolov8m_post_train
seed: 42
project: cv_module/models
half: true
optimizer: adamw
lr0: 0.0005
lrf: 0.0005
warmup_epochs: 1
close_mosaic: 0
freeze: 0

